# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/infra3vladalinbosii.duckdns.org
cert = /etc/letsencrypt/live/infra3vladalinbosii.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/infra3vladalinbosii.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/infra3vladalinbosii.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/infra3vladalinbosii.duckdns.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 3251047ae12f984bdeaad8311eb877bb
pref_challs = dns-01,
authenticator = dns-duckdns
dns_duckdns_token = 4c29cb1e-7f1c-4dd8-96e1-204027ef8c2d
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
