# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/vladalinbosiiproject.duckdns.org
cert = /etc/letsencrypt/live/vladalinbosiiproject.duckdns.org/cert.pem
privkey = /etc/letsencrypt/live/vladalinbosiiproject.duckdns.org/privkey.pem
chain = /etc/letsencrypt/live/vladalinbosiiproject.duckdns.org/chain.pem
fullchain = /etc/letsencrypt/live/vladalinbosiiproject.duckdns.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 2038e2c87c20c586792c4407d120aeb7
pref_challs = dns-01,
authenticator = dns-duckdns
dns_duckdns_token = 2dfd5064-41c6-4d63-b560-9df0219e4b00
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
